services:
  flexit-webserver:
    container_name: flexit-webserver
    image: jwilder/nginx-proxy
    restart: unless-stopped
    networks:
      - flexit-network
    ports:
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERT_PATH}/certificates:/etc/nginx/certs
      - ./nginx/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf:ro
networks:
  flexit-network:
