services:
  flexit-analytics:
    platform: linux/amd64
    container_name: flexit-analytics
    hostname: ${PUBLIC_DNS}
    networks:
      - flexit-network
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/flexanalytics/flexit:${FLEXIT_VERSION}
    pull_policy: missing
    env_file: .env
    restart: unless-stopped
    depends_on:
      flexit-content-database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@flexit-content-database:5432/${DB_NAME}
      NODE_ENV: development
      PORT: ${FLEXIT_PORT}
      VIRTUAL_HOST: ${PUBLIC_DNS}
      VIRTUAL_PORT: 3030
      LETSENCRYPT_HOST: ${PUBLIC_DNS}
      LETSENCRYPT_EMAIL: ${CERT_EMAIL}

    ports:
      - "${FLEXIT_PORT}:3030"
    volumes:
      - flexit_config:/opt/flexit/config
      - flexit_datasets:/opt/flexit/datasets
      - flexit_deployments:/opt/flexit/deployments
      - flexit_logs:/opt/flexit/logs
      - flexit_webcontent:/opt/flexit/webcontent

  flexit-content-database:
    container_name: flexit-content-database
    image: postgres:15
    restart: unless-stopped
    networks:
      - flexit-network
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  flexit_config:
    name: flexit_config
  flexit_datasets:
    name: flexit_datasets
  flexit_deployments:
    name: flexit_deployments
  flexit_logs:
    name: flexit_logs
  flexit_webcontent:
    name: flexit_webcontent
  postgres_data:
    name: postgres_data

networks:
  flexit-network:
    name: flexit-network
    driver: bridge
