services:
  flexit-webserver-proxy:
    container_name: flexit-webserver-proxy
    image: nginxproxy/acme-companion
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    networks:
      - flex-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERT_PATH}:/etc/nginx/certs
networks:
  flexit-network:
    external: true
