services:
  flexit-webserver-proxy:
    image: goacme/lego:latest
    container_name: flexit-webserver-proxy
    entrypoint: /bin/sh
    command: >
      -c "if [ -f /etc/lego/certificates/${PUBLIC_DNS}.crt ]; then
            echo 'Renewing certificate...';
            /lego --email ${CERT_EMAIL} --domains ${PUBLIC_DNS} --tls --path /etc/lego --accept-tos renew;
          else
            echo 'Running initial issuance...';
            /lego --email ${CERT_EMAIL} --domains ${PUBLIC_DNS} --tls --path /etc/lego --accept-tos run;
          fi"
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERT_PATH}:/etc/nginx/certs
