services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    networks:
      - flex-network
    ports:
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERT_PATH}:/etc/nginx/certs

