services:
  flexit-webserver-proxy:
    container_name: flexit-webserver-proxy
    image: nginxproxy/acme-companion
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    networks:
      - flex-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CERT_PATH}:/etc/nginx/certs
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ${CERT_PATH}:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: ${CERT_EMAIL}
      NGINX_PROXY_CONTAINER: nginx-proxy
